server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: http://git.yashijitv.com/platform-cloud/config.git
          username: platform
          password: 7pnF6NnADwGP
  application:
    name: platform-cloud-config
#  security:
#    user:
#      name: platform
#      password: 7pnF6NnADwGP
